# Generated by Django 5.2.3 on 2025-09-01 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
