# Generated by Django 5.2.3 on 2025-09-09 09:04

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_adminprofile_created_at_adminprofile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('completed', 'اتمام'), ('recording', 'در حال ضبط'), ('soon', 'بزودی')], max_length=20)),
                ('thumbnail', models.ImageField(upload_to='packages/thumbnails/')),
                ('is_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='accounts.adminprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasers', to='education.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('is_free', models.BooleanField(default=False)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='education.package')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_active', '-created_at'], name='education_p_is_acti_038f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_free'], name='education_p_is_free_456e68_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['-view_count'], name='education_p_view_co_054f52_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['-popularity_score'], name='education_p_popular_ee1dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['user', 'package'], name='education_u_user_id_1fc1dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpackage',
            unique_together={('user', 'package')},
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['package'], name='education_v_package_09386a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_free'], name='education_v_is_free_3c1ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-created_at'], name='education_v_created_fba71b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('package', 'slug')},
        ),
    ]
