# Generated by Django 5.2.3 on 2025-09-14 13:33

import ckeditor_uploader.fields
import education.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('package', 'slug', 'title')},
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=education.models.video_upload_to),
        ),
        migrations.RemoveField(
            model_name='video',
            name='download_count',
        ),
    ]
